export const TESTIMONIALS_DATA = [
  {
    tagEs: "PUBLICIDAD AMAZON",
    tagEn: "AMAZON PPC",
    textEs: "TRABAJAR CON ESTE EQUIPO FUE UNA EXPERIENCIA TRANSFORMADORA PARA NUESTRA MARCA. SU EXPERIENCIA EN PUBLICIDAD DE AMAZON Y ESTRATEGIAS DE PUJA INTELIGENTE NOS AYUDÓ A MANTENERNOS POR DELANTE DE LA COMPETENCIA Y MEJORÓ SIGNIFICATIVAMENTE NUESTRO RENDIMIENTO EN LA PLATAFORMA. BRINDARON UN SOPORTE EXCEPCIONAL, COMUNICACIÓN CLARA E INFORMACIÓN VALIOSA EN CADA PASO DEL CAMINO. SU ENFOQUE PERSONALIZADO HA LLEVADO A UN CRECIMIENTO SOSTENIDO Y UNA MAYOR RENTABILIDAD. LOS RECOMIENDO AMPLIAMENTE.",
    textEn: "WORKING WITH THIS TEAM WAS A TRANSFORMATIVE EXPERIENCE FOR OUR BRAND. THEIR EXPERTISE IN AMAZON ADVERTISING AND SMART BIDDING STRATEGIES HELPED US STAY AHEAD OF COMPETITORS AND SIGNIFICANTLY BOOSTED OUR PERFORMANCE ON THE PLATFORM. THEY PROVIDED EXCEPTIONAL SUPPORT, CLEAR COMMUNICATION, AND VALUABLE INSIGHTS EVERY STEP OF THE WAY. THEIR TAILORED APPROACH HAS LED TO SUSTAINED GROWTH AND IMPROVED PROFITABILITY. HIGHLY RECOMMEND THEM.",
    name: "AGUSTIN JANOTER",
    roleEs: "CEO EN MARSIP",
    roleEn: "CEO AT MARSIP",
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80"
  },
  {
    tagEs: "OPTIMIZACIÓN",
    tagEn: "OPTIMIZATION",
    textEs: "NOS ASOCIAMOS CON ELLOS PARA OPTIMIZAR NUESTRAS CAMPAÑAS DE AMAZON Y LOS RESULTADOS HAN SIDO EXCEPCIONALES. SU PROFUNDO CONOCIMIENTO DE LA PLATAFORMA DE AMAZON Y SUS ESTRATEGIAS EXPERTAS LLEVARON A UN AUMENTO SIGNIFICATIVO EN LAS VENTAS Y LA VISIBILIDAD. SU EQUIPO ES PROFESIONAL, RECEPTIVO Y COMPROMETIDO A OFRECER RESULTADOS TANGIBLES. RECOMIENDO ALTAMENTE SUS SERVICIOS PARA CUALQUIERA QUE BUSQUE ESCALAR SU NEGOCIO DE AMAZON DE MANERA EFECTIVA.",
    textEn: "WE PARTNERED WITH THIS TEAM TO OPTIMIZE OUR AMAZON CAMPAIGNS, AND THE RESULTS HAVE BEEN OUTSTANDING. THEIR DEEP UNDERSTANDING OF AMAZON'S PLATFORM AND EXPERT STRATEGIES LED TO A SIGNIFICANT INCREASE IN SALES AND VISIBILITY. THEIR TEAM IS PROFESSIONAL, RESPONSIVE, AND COMMITTED TO DELIVERING TANGIBLE RESULTS. HIGHLY RECOMMEND THEIR SERVICES FOR ANYONE LOOKING TO SCALE THEIR AMAZON BUSINESS EFFECTIVELY.",
    name: "EZEQUIEL RAMIREZ",
    roleEs: "DIRECTOR DE MARKETING EN SHAPERMINT",
    roleEn: "MARKETING DIRECTOR AT SHAPERMINT",
    image: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&auto=format&fit=crop&q=80"
  },
  {
    tagEs: "CRECIMIENTO",
    tagEn: "GROWTH",
    textEs: "SU EQUIPO HA SIDO UN CAMBIO DE JUEGO PARA NUESTRO NEGOCIO EN AMAZON. SU EQUIPO SE TOMÓ EL TIEMPO PARA COMPRENDER NUESTRA MARCA Y DISEÑÓ UNA ESTRATEGIA QUE MAXIMIZÓ NUESTRO RETORNO DE LA INVERSIÓN PUBLICITARIA (ROAS). HEMOS VISTO UNA MEJORA NOTABLE EN EL TRÁFICO, LAS CONVERSIONES Y LAS VENTAS EN GENERAL. NO SON SÓLO UN PROVEEDOR DE SERVICIOS, SON UN VERDADERO SOCIO EN NUESTRO CRECIMIENTO. NO PODRÍAMOS ESTAR MÁS SATISFECHOS CON LOS RESULTADOS.",
    textEn: "THIS TEAM HAS BEEN A GAME-CHANGER FOR OUR AMAZON BUSINESS. THEIR TEAM TOOK THE TIME TO UNDERSTAND OUR BRAND AND TAILORED A STRATEGY THAT MAXIMIZED OUR RETURN ON AD SPEND (ROAS). WE'VE SEEN A NOTICEABLE IMPROVEMENT IN TRAFFIC, CONVERSIONS, AND OVERALL SALES. THEY’RE NOT JUST A SERVICE PROVIDER—THEY’RE A TRUE PARTNER IN OUR GROWTH. WE COULDN’T BE MORE SATISFIED WITH THE RESULTS.",
    name: "MELISSA J.",
    roleEs: "PROPIETARIA DE MARCA EN BROOKTHORNE",
    roleEn: "BRAND OWNER AT BROOKTHORNE",
    image: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=200&auto=format&fit=crop&q=80"
  }
];
